Adds wxSimpleBook XRC export code.
wxFormBuilder/wxFormBuilder pull request #668
Opened 2021-04-17 21:47 UTC by OmniBlade

Implements the missing XRC import/export code in plugins/containers/container.cpp.
Fixes #666

2021-04-19 18:38 UTC, sodevel requested changes
This is looking good, there are just some minor formatting issues, it would be nice if you could fix them.

2021-04-19 18:38 UTC, sodevel commented on plugins/containers/containers.cpp
> +		xrc.AddProperty(_("select"),_("selected"),XRC_TYPE_BOOL);
Space after comma missing

2021-04-19 18:38 UTC, sodevel commented on plugins/containers/containers.cpp
> +		filter.AddProperty(_("selected"),_("select"),XRC_TYPE_BOOL);
Space after comma missing

2021-04-20 12:09 UTC, OmniBlade commented
Looks like the spacing issues is prevelent in the file as I just copy pasted those sections and modified them :D I've fixed them now, but left the rest of the file as is so the PR just reflects the functional change.

2021-04-20 21:25 UTC, sodevel commented
Formatting is kind of a mess in the code base, the long term goal is to implement a format specification to allow automatic formatting of the code. The difficulty is to find a free solution that works on all three platforms easily, so far i only know about clang-format, but i am quite unhappy with some of the results it produces.

Anyway, thanks for the PR, i fixed the introduced whitespace errors myself.

2021-04-20 21:26 UTC, merged