add support for wxVListBox
wxFormBuilder/wxFormBuilder pull request #858
Opened 2024-11-09 06:23 UTC by wsu-cb

Fix #857

2024-11-09 06:48 UTC, wsu-cb commented
This pull request depends on wxWidgets commit 12b09a5e5ea76a1a0c27b769e821b37d803a4cb7.

2024-11-10 22:09 UTC, sodevel commented
This PR is marked as draft, so i don't know if i am supposed to comment on it already, so i give only two small remarks.

The dependency on https://github.com/wxWidgets/wxWidgets/commit/12b09a5e5ea76a1a0c27b769e821b37d803a4cb7 is only for the generated code, and only if that specific control is used, so this is fine, wxFB usually tries to target the latest wxWidgets build.

The failing CI seems to be caused only by the usage of `wxInfoDC`, IIRC this is also a very recent addition to wxWidgets, this is problematic. Some platforms (looking at you, Ubuntu) need ages to update wxWidgets, such a compile dependency will break wxFB for such platforms for a long time. I suggest to protect this code path with a version check and add another path which uses `wxClientDC`.

2024-11-10 22:29 UTC, wsu-cb commented
> This PR is marked as draft, so i don't know if i am supposed to comment on it already, so i give only two small remarks.
> 

I had marked this draft since I thought I should try to figure out the build problems before asking for a review.  However, I am more than happy to have your comments, and thank you for taking the time to investigate.

2024-12-09 05:10 UTC, wsu-cb commented
How do I request a review of this PR?

2024-12-10 01:06 UTC, sodevel commented
You don't have to, i have seen your PR. Unfortunately i am still very busy with real life issues and don't have the time yet to take care of the outstanding PR's and other pending features. I am not sure if i can process them before the holidays, so it might still take some time.

2024-12-10 03:55 UTC, wsu-cb commented
> You don't have to, i have seen your PR. Unfortunately i am still very busy with real life issues and don't have the time yet to take care of the outstanding PR's and other pending features. I am not sure if i can process them before the holidays, so it might still take some time.

OK.

2025-01-25 19:03 UTC, sodevel requested changes
Sorry for the late reply, i found only now some time to process outstanding PRs.

Thank you for adding code templates for all languages, this doesn't happen often. Did you actually check if all languages do support that control or did you just add the templates according to the used pattern of these languages?

Unfortunately the preview in the designer doesn't work as intended i think, my control is always empty. It should contain some dummy entries like e.g. wxGrid does. But this shouldn't be hard to fix.

Please see the following review for details.

2025-01-31 05:17 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +    class wxVListBoxExample : public wxVListBox
Done.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/38a63090756ecc2798c5e12cea1e2202a2eca2e5

2025-01-31 05:18 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        virtual wxCoord OnMeasureItem(size_t n) const override;
Done.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/44bd02a0e25e469dc96069838d878c2e17f86370

2025-01-31 05:19 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        wxDECLARE_DYNAMIC_CLASS(wxVListBoxExample);
This is needed to support XRC Preview.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/7d8f60b3a435e059cd291f0c4cb560ca87e390d6

2025-01-31 05:20 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        void OnCreate(wxWindowCreateEvent& event);
XRC Preview needs this.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/7d8f60b3a435e059cd291f0c4cb560ca87e390d6

2025-01-31 05:20 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +    wxIMPLEMENT_DYNAMIC_CLASS(wxVListBoxExample, wxVListBox);
XRC Preview needs this.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/7d8f60b3a435e059cd291f0c4cb560ca87e390d6

2025-01-31 05:20 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +    wxEND_EVENT_TABLE()
XRC Preview needs this.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/7d8f60b3a435e059cd291f0c4cb560ca87e390d6

2025-01-31 05:23 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        SetItemCount(std::numeric_limits<size_t>::max());
The preview was empty because a bug prevented this from being called.  The bug is fixed in https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/3895a20514d680c4760d0d6855a4b8b3c8ee3bde.  However, the `size_t` limit is also wrong because the `wxVListBox` API is inconsistent about using `size_t` and `int`.  Fixed in https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/b44c80c1ce1be5d86b0656283aa068ea03249d7c

2025-01-31 05:25 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +
I call `SetItemCount()` in the `EVT_WINDOW_CREATE` handler instead so that it will also be called for XRC Preview

2025-01-31 05:28 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +    }
As of wxWidgets master branch commit 12b09a5e5ea76a1a0c27b769e821b37d803a4cb7, XRC does support wxVListBox.  (For me, that's the point of adding wxVListBox support to wxWidgets.)  However, I admit I didn't update [XRC File Format](https://docs.wxwidgets.org/latest/overview_xrcformat.html).

2025-01-31 05:29 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +#include <wx/vlbox.h>
Done.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/66de2f3a0adc267f05a4f3f9fe41e23393d1ecb9

2025-01-31 05:39 UTC, wsu-cb commented
> Thank you for adding code templates for all languages, this doesn't happen often. Did you actually check if all languages do support that control or did you just add the templates according to the used pattern of these languages?
> 

The only version I actually use is XRC.  For the other languages I just tried to imitate the existing templates.

> Unfortunately the preview in the designer doesn't work as intended i think, my control is always empty. It should contain some dummy entries like e.g. wxGrid does. But this shouldn't be hard to fix.
> 
> Please see the following review for details.

That's a bug due to the order of C++ object construction not being compatible with one-step window creation for a derived class.  The Bug is fixed in https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/3895a20514d680c4760d0d6855a4b8b3c8ee3bde.

2025-01-31 05:41 UTC, wsu-cb commented
I do not understand the Flatpak build failure.  Can anyone give me some help?

2025-02-01 04:53 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        wxVListBoxPreview() = default;
I have realized that there is another solution to the problem that would enable both one-step and two-step creation, at the cost of a small amount of additional code:  If a one-step constructor is declared in this class, it will allow the `vtable` to be set before `Create()` is called.  Do you have a preference between the current, shorter code, or the alternative longer code that supports one-step creation?

2025-02-01 07:10 UTC, sodevel commented
> I do not understand the Flatpak build failure. Can anyone give me some help?

You can ignore this error. The author of the GitHub Action that creates the Flatpak still hasn't updated it and GitHub now disabled the used upload endpoint. If he doesn't update it soon, i'm going to switch to a fork that is hopefully better maintained.

2025-02-01 07:36 UTC, sodevel commented on plugins/additional/additional.cpp
> +        wxVListBoxPreview() = default;
I think the root cause of the no-items issue is that the event gets processed when still inside the constructor. I think this can be solved by using `CallAfter()` instead. If you define the default constructor like this

```cpp
wxVListBoxPreview() { CallAfter([this] { SetItemCount(20); }); }
```

it should work, no need for a event table. The parameterized constructor could call the default constructor as delegate so you don't need to add that call there as well. Also please use a smaller item count than maximum integer, there is just no scrollbar thumb visible in that case.

2025-02-01 07:37 UTC, sodevel commented on plugins/additional/additional.cpp
> +    }
Ah thanks, i missed that

2025-02-01 08:20 UTC, sodevel requested changes
This review is targeted at your last commit and tries to answer your question.

I am perfectly fine if the XRC preview inside wxFB does not support the control. Like the warning dialog of the preview says, this is a best effort preview and might differ from the final result, inside wxFB much more can be designed than XRC can realize.

You already invested quite some work to get a working preview, if you are willing to invest more work, currently only one "proper" solution that has not so bad side effects comes into my mind, but i am not sure if it is possible at all, there are two questions about it i can't answer myself right now.

The idea is to write an own `wxXmlResourceHandler` that always creates the preview class. Now the question is, this handler would handle the very same object class like the one you added to wxWidgets already, can you override this one with that new handler? Looking at the documentation of `wxXmlResource::InsertHandler(wxXmlResourceHandler *handler)` i would guess yes. The next question is can you prevent the subclassing feature to happen or prevent to cause an error if it fails and replace the possible already created object with the preview object?

If it is possible to create such a `wxXmlResourceHandler` you could implement it in the plugin source file and register it between the `BEGIN_LIBRARY()` and `END_LIBRARY()` calls at the bottom on the file.

2025-02-01 09:10 UTC, sodevel commented
Looks like with [wxXRC_NO_SUBCLASSING](https://docs.wxwidgets.org/latest/xmlres_8h.html#ad36a879ef645d6ee478f118b211d9431ae71f919b25bccff3de8c1ac5faa94ace) subclassing can be disabled which is exactly what is needed. In https://github.com/wxFormBuilder/wxFormBuilder/commit/11b37992e5afc69245343256832ad96965fb05cd you can see where this flag can be set. Hmm, there you can also see that everytime the preview is opened all handlers get added, this doesn't look good, i need to investigate.

2025-02-01 19:49 UTC, wsu-cb commented
> Looks like with [wxXRC_NO_SUBCLASSING](https://docs.wxwidgets.org/latest/xmlres_8h.html#ad36a879ef645d6ee478f118b211d9431ae71f919b25bccff3de8c1ac5faa94ace) subclassing can be disabled which is exactly what is needed. In [11b3799](https://github.com/wxFormBuilder/wxFormBuilder/commit/11b37992e5afc69245343256832ad96965fb05cd) you can see where this flag can be set.

Unfortunately, I think it is desirable for wxFormBuilder to use `wxXRC_NO_SUBCLASSING` in every case EXCEPT for `wxVListBox`.  The problem is that `wxVListBox` is a pure abstract class, and so MUST be subclassed.  I would really like the XRC Preview to be able to show an actual control rather than fail for `wxVListBox`.  Unfortunately, all other classes with a subclass will fail if `wxXRC_NO_SUBCLASSING` is not used.  I need to take this discussion to the wx-dev discussion list...

2025-02-01 21:00 UTC, wsu-cb commented on plugins/additional/additional.cpp
> +        wxVListBoxPreview() = default;
Done.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/1c08a58e05a52629c18d66e1678285cdf8177814.

However, I think you should report the no-visible-thumb problem to wxWidgets as a bug.  On my system (wxMSW, Windows 10 22H2), the thumb shows at the normal size with max_int items.

2025-02-01 21:27 UTC, sodevel commented on plugins/additional/additional.cpp
> +        wxVListBoxPreview() = default;
I only used the wxFB build from GitHub on my Windows 11 machine, i just did another test with a regular wxListBox, there the scrollbar thumb is also missing, even when there are only a few items in it. Seems to be a generic problem specific to the Windows 11 "smart" scroll bars. After some more testing i figured out this happens when the scrollbar gets too small. The default height of the preview item is 50 pixels, at 60 pixels i get the thumb, even for your max int count of items.

![wxfb-scrollbars](https://github.com/user-attachments/assets/e661da50-4ede-45eb-a2c2-8502f7149bc8)

2025-02-01 21:35 UTC, sodevel commented
> Unfortunately, I think it is desirable for wxFormBuilder to use `wxXRC_NO_SUBCLASSING` in every case EXCEPT for `wxVListBox`. The problem is that `wxVListBox` is a pure abstract class, and so MUST be subclassed.

And because of that my idea is to write an own xrc resource handler inside the wxFB plugin which can see the preview class and always instantiates this instead of the abstract class like the default xrc resource handler of wxWidgets would do in that case. This only works if you can override the default xrc resource handler which i think should be possible. Of course this will kind of break the xrc resource loading inside wxFB for that class, but wxFB currently does not use xrc for itself. And even if it would do sometime, regarding the comments in the documentation of the wxXmlResource class, it should be possible to use an own instantiation of this instead of using the global singleton one.

2025-02-02 03:45 UTC, wsu-cb commented
> The idea is to write an own `wxXmlResourceHandler` that always creates the preview class. Now the question is, this handler would handle the very same object class like the one you added to wxWidgets already, can you override this one with that new handler? Looking at the documentation of `wxXmlResource::InsertHandler(wxXmlResourceHandler *handler)` i would guess yes. The next question is can you prevent the subclassing feature to happen or prevent to cause an error if it fails and replace the possible already created object with the preview object?
> 
> If it is possible to create such a `wxXmlResourceHandler` you could implement it in the plugin source file and register it between the `BEGIN_LIBRARY()` and `END_LIBRARY()` calls at the bottom on the file.

I have attempted implement this, and I think it ALMOST works.  The problem is that I don't see a way to unregister a `wxXmlResourceHandler`, and the plugin gets unloaded before wxWidgets does its automatic cleanup of the registered handlers.  When the cleanup code deletes my `wxXmlResourceHandler`, the system tries to execute the destructor code in the already-unloaded plugin.  This results in a crash, so I think this idea can't work without modifications to wxWidgets.

2025-02-02 05:24 UTC, sodevel commented
I don't know if wxFB unload the plugins manually or relies on automatic unloading, but if this is really the cause of your crash, there should be some cleanup code that ensures that all components created by plugins get deleted before the unloading happens, otherwise there should be a crash because of the very same reason.

While wxWidgets does not have a method to delete a specific xrc handler, it has a method to delete all xrc handlers. Since wxFB gets shutdown anyway and doesn't use XRC at all but for the preview window, there should be no harm done if all xrc handlers get deleted. If i find some time, maybe i can look for a good cleanup location myself, i already should look for a good init location anyway.

2025-02-02 23:47 UTC, sodevel commented
I just pushed a commit that deletes all xrc resource handlers before the plugins get unloaded, this prevents the crash you observed. If you rebase this PR against current master you not only get that fix, but also you can compile wxFB against latest wxWidgets master.

2025-02-03 00:27 UTC, wsu-cb commented
We are having a [discussion on wx-dev mailing list about this](https://groups.google.com/g/wx-dev/c/M45iC79byoA/m/Rwdxe0qnCgAJ), so I will hold off on doing anything more with this PR until the wx-dev discussion concludes.

2025-02-09 06:48 UTC, wsu-cb commented
As of https://github.com/wxWidgets/wxWidgets/commit/f2d5aca264735192a10928e9b701da2297c3b77c, wxWidgets master branch provides `wxXRCPreviewVListBox`, and the wxWidgets XRC loader will automatically provide that class when in `wxXRC_NO_SUBCLASSING` mode.  I have updated this PR accordingly.

2025-02-10 18:19 UTC, sodevel requested changes
Thanks for the update, this is looking good, i have only two small notes about the implementation itself but also one bigger topic to think about.

Since you guarded the whole component class with a version check, the objectinfo definition should be guarded as well (see below), otherwise you get some warnings in the debug log (i just fixed master to prevent user visible errors if the version check is enabled).

It is a bit unfortunate that the preview class of wxWidgets does not specifiy a visible best size, since by default wxFB uses wxDefaultSize, the preview is invisible in wxFB until a size is specified or expansion is enabled. But since that class is part of wxWidgets now, i guess it is hard to find a size that fits all.

Now the bigger topic, the wxWidgets release cycle. The official wxFB releases are build by GitHub and use only released wxWidgets versions. There are also quite a few Linux distributions that offer wxFB and these also use only released versions, in the past they skipped development releases so the next version Linux will pick up might be wxWidgets 3.4 only. Since your wxWidgets additions are targeted for wxWidgets 3.3, which should have been released last year according to their website but still wasn't, and it is unknown if they will be backported to wxWidgets 3.2, current wxFB releases don't contain the wxVListBox control. For Windows and macOS it might take some months until a supporting wxWidgets release is available, for Linux it might take multiple years even. So to get support for wxVListBox users need to compile wxFB themself. However, unless you need XRC support, current wxWidgets supports wxVListBox very well.

Maybe you should consider to add a second code path for pre-wxWidgets 3.3 versions so that the control is available inside wxFB today. You probably can take the code you added to wxWidgets and wrap it into an anonymous namespace almost unmodified and just add the registration of the XRC handler.

2025-02-14 04:50 UTC, wsu-cb commented
> Maybe you should consider to add a second code path for pre-wxWidgets 3.3 versions so that the control is available inside wxFB today. You probably can take the code you added to wxWidgets and wrap it into an anonymous namespace almost unmodified and just add the registration of the XRC handler.

Done.  See https://github.com/wxFormBuilder/wxFormBuilder/pull/858/commits/3d2ff01718e82567d489bf0d19280eb32cd04a6c

2025-02-14 04:51 UTC, wsu-cb commented on plugins/additional/xml/additional.xml
> +  <objectinfo class="wxVListBox" icon="list_box.xpm" type="widget">
I added `wxVListBox` support for wxWidgets < 3.3, so I think this no longer makes sense.

2025-02-19 01:45 UTC, wsu-cb commented
> Thanks for the update, there are again some virtual and override specifiers together, but i can fix this myself like i will fix the formatting in a future mass reformatting.

That's the wxWidgets code style (see, e.g., https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/xrc/xh_listb.h and https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/msw/window.h), and I just copied the wxWidgets code here.  However, now that you remind me that wxFormBuilder drops the virtual specifiers, I can do that when I update the size issue below.

>I have seen you made a PR to wxWidgets to address the sizing issue, have you planned to integrate this into the alternate code path here as well once it got merged?

That was my intent, but I admit it had slipped my mind, so thank you for the reminder.

2025-02-24 00:46 UTC, sodevel approved these changes
This is looking good. Thank you for the updates and your patience, i am going to merge this now.

2025-02-24 00:47 UTC, merged